### ISSUE TITLE
Is there a way for me to run it without installing the Jmeter

### ISSUE THREAD

**Issue by vikram-rawat** [tmobile/loadtest#18]
Like, is it possible for me just to point to the bin folder of Jmeter and get it rolling rather than setting it up in the environment variable? That would be easier for everybody who works in a corporate setting where asking for installation permission takes days.

something like what sparklyR does...

Please do let me know.

**Comment by meztez** [comment]
```R
# devtools::install_github("tmobile/loadtest")
# install java and jmeter - hourray /s
Sys.setenv("LOADTEST_JMETER_PATH"="C:/Program Files/apache-jmeter/bin/jmeter")

library(loadtest)
```

It's in the doc

https://github.com/tmobile/loadtest/blob/93f6d4e338fd27a0e7e7d42f54c19860d1980321/README.md#installing-jmeter

**Comment by vikram-rawat** [comment]
Thanks for pointing it out. But even after using it my code doesn't work.

```
library(loadtest)
Sys.setenv("LOADTEST_JMETER_PATH"="C:\\Users\\vikram.rawat\\Downloads\\apache-jmeter-5.3\\bin")
loadtest:::check_jmeter_installed()
results <- loadtest(url = url,
                    method = "GET",
                    # headers = c("version"="v1.0"),
                    # body = list(sentences = list("I love this band")),
                    # encode="json",
                    threads = 8,
                    loops = 32,
                    delay_per_request=100)

```

it gives me an error.

```
loadtest - beginning load test
loadtest - completed load test
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: In doTryCatch(return(expr), name, parentenv, handler) :
  Unable to find JMeter installation. https://github.com/tmobile/loadtest#installation
2: In file(file, "rt") :
  cannot open file 'C:\Users\VIKRAM~1.RAW\AppData\Local\Temp\RtmpKqhWBa\file5c903cec5f88.csv': No such file or directory
```
However the ` httr::GET(url = url) `  request works with result. I can assure that URL is working fine.
```
Response [http://localhost:9090/api/dimensions/country]
  Date: 2020-10-14 21:01
  Status: 200
  Content-Type: text/plain
  Size: 158 B
```

**Comment by vikram-rawat** [comment]
This worked for me... Thanks for replying.. and I sorry to not go through the entire document before asking straight away... We can close this I guess

**Comment by meztez** [comment]
@vikram-rawat I guess you can close it.

**Comment by vikram-rawat** [comment]
Thanks for helping me

**Comment by acircleda** [comment]
Just installed. You should clarify in the readme that it's not just the path to `bin` but `bin/jmeter`. That got it working for me, even though `jmeter --version` worked.
