### ISSUE TITLE
feature request: tell user when test starts and stops

### ISSUE THREAD

**Issue by nolistic** [tmobile/loadtest#3]
currently, the output while running the actual load test looks like this 
![image](https://user-images.githubusercontent.com/24787005/65544397-fada9d00-dec7-11e9-9c60-7a90b5bc66ee.png)

I want it to alert me when it starts and do something better than "... test over I guess"

one of the only java cultural relics I will stand behind is the ascii art that lets you know something is starting up, so bonus points for that
![image](https://user-images.githubusercontent.com/24787005/65544155-856ecc80-dec7-11e9-9bc1-6febc2ed2e2b.png)

**Comment by jnolis** [comment]
Are these the dark arts you crave?
![image](https://user-images.githubusercontent.com/3317138/65642645-ac4f0080-dfa4-11e9-8c8b-2ba83cb6d400.png)
