### ISSUE TITLE
Cannot Open CSV File Error

### ISSUE THREAD

**Issue by QAInsights** [tmobile/loadtest#7]
I have installed all the prerequisite and executed the below snippet. But I am getting the below error.

`cannot open file 'C:\Users\Public\Documents\Wondershare\CreatorTemp\RtmpAvehNO\filefab832c3f55.csv': No such file or directory`

**Defect details**
OS: Windows 10
R: 64 bit 3.6.1
JMeter: 5.2
IDE 1: VS Code 1.40.0
IDE 2: RGui

**R Snippet**

```
Sys.setenv("LOADTEST_JMETER_PATH"="C:\\apache-jmeter-5.2")
install.packages("remotes")
remotes::install_github("tmobile/loadtest")
library(loadtest)

results <- loadtest(url = "http://deepmoji.teststuff.biz",
  method = "POST",
  body = list(sentences = list("I love this band")),
  threads = 8,
  loops = 32)
```

When I execute the above snippet in VS Code as well as in RGui, it is failing. However, it is creating the JMX file in the below path. Not sure why it is picking **Wondershare** folder.

`C:\Users\Public\Documents\Wondershare\CreatorTemp\Rtmp8cbIgd`

When I open the JMX file in JMeter, it has **Simple Data Write** element with the path `C:\Users\Public\Documents\Wondershare\CreatorTemp\Rtmp8cbIgd\fileb92c2bdb5c9f.csv` which is not creating during runtime.

I have granted write access to the **Wondorshare** folder manually. But it is not working. Here is the complete log.

```
> source("c:\\Users\\Navee\\OneDrive\\Documents\\Tools\\R\\test.r", encoding =$
Installing package into 'C:/Users/Navee/OneDrive/Documents/R/win-library/3.6'
(as 'lib' is unspecified)
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.6/remotes_2.1.0.zip'
Content type 'application/zip' length 354910 bytes (346 KB)
downloaded 346 KB

package 'remotes' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\Public\Documents\Wondershare\CreatorTemp\Rtmpy8G8dC\downloaded_packages
Skipping install of 'loadtest' from a github remote, the SHA1 (a9ae521d) has not changed since last install.
  Use `force = TRUE` to force installation
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: In system2(jmeter_path(), args = c("-n", "-t", spec_location, "-l",  :
  'CreateProcess' failed to run 'C:\apache-jmeter-5.2 -n -t C:\Users\Public\Documents\Wondershare\CreatorTemp\Rtmpy8G8dC\file8af04f624a8b.jmx -l C:\Users\Public\Documents\Wondershare\CreatorTemp\Rtmpy8G8dC\file8af05ee8169a.csv'
2: In file(file, "rt") :
  cannot open file 'C:\Users\Public\Documents\Wondershare\CreatorTemp\Rtmpy8G8dC\file8af05ee8169a.csv': No such file or directory
```

**Comment by QAInsights** [comment]
UPDATE: Load test is happening if I set the environment variable pointing to the .bat file.

**Sys.setenv("LOADTEST_JMETER_PATH"="C:\\apache-jmeter-5.2\\bin\\jmeter.bat")**

**Comment by jnolis** [comment]
I'm glad you got it working. I'll see if I can update the documentation/error handling to make this situation clearer. There should have been an error that jmeter wasn't referenced correctly, but for some reason it didn't fire off.

**Comment by QAInsights** [comment]
@jnolis Could you please clarify why the temp folder is set to `Wondershare`, I have Wondershare software installed. Not sure what folder it would pick up by default. Please enlighten me.

**Comment by QAInsights** [comment]
@jnolis Here is [my blog article](https://qainsights.com/performance-testing-in-r-using-apache-jmeter/)  about `loadtest`

**Comment by jnolis** [comment]
The way the package figures out how jmeter is install is by using the `Sys.which()` command in R. That command looks for the path of calling a function from the command line. By default loadtest looks for "jmeter" but if you change that environmental variable for the location of jmeter it uses that instead. On my windows machine I get:

```
> Sys.which("jmeter")
                                         jmeter 
"C:\\PROGRA~1\\Apache\\jmeter\\bin\\jmeter.bat"
```

If you run it perhaps it gives Wondershare in the path. If so that might have to do with how you set the path variables on your machine (depending on your OS).

Thanks for the blog writeup! I never would have thought to run loadtest from VS Code but that's a great idea.
